### ISSUE TITLE
Skrivefeil

### ISSUE THREAD

**Issue by geira** [nrkno/yr-weather-symbols#16]
Fikk denne på api-support:

> Hei jeg ser på dokumentasjonen og her beskrives da både lightssleetshowersandthunder og lightssnowshowersandthunder. Er dette riktig? For meg virker det som det er en ekstra s her:
>
>> light s sleet showers and thunderlight s snow showers and thunder
>
> Det er jo vitterlig lightsnowshowers og lightsleetshowers, altså uten ekstra s, så hvorfor skulle man ha med en ekstra s når man legger ved “andthunder” på akkurat disse to?

**Comment by esseb** [comment]
Har fikset dette nå.
