### ISSUE TITLE
Relative weather scale

### ISSUE THREAD

**Issue by mattarderne** [nrkno/yr-weather-symbols#21]
Hello

I am interested in a relative scale of all of the possible weather symbols, as per the below version of the README.md file, where a `relative_scale` field is added. This gives an ability rank the weather symbols. Eg `Light rain showers and thunder` is fairer weather than `Light sleet showers and thunder`.

https://github.com/mattarderne/yr-weather-symbols/blob/master/README.md

Has anything like this been done before? This obviously has issues with interpretation and preference, but my use is of a broad relative rating, as I've created.

**Comment by esseb** [comment]
The weather symbol data/ids we use on yr.no come from the Norwegian Meteorological Institute (MET) originally, and the relative ranking you want would make more sense to include in their API, see https://api.met.no/weatherapi/weathericon/2.0/documentation

MET will be better able to answer your question, they have a contact page on https://api.met.no/doc/support
